FROM python:3.12.14-slim-trixie@sha256:2c941e860699f878900b0edc2403613c234d4b32eda3cc9fa7036991a2a63c4a
WORKDIR /app
RUN pip install --no-cache-dir fastapi uvicorn
COPY fake_worker.py .
EXPOSE 30000
CMD ["python", "fake_worker.py"]
